/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACol: typeof import('ant-design-vue/es')['Col']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    ARow: typeof import('ant-design-vue/es')['Row']
    ATable: typeof import('ant-design-vue/es')['Table']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarMenu: typeof import('./src/components/layout/SidebarMenu.vue')['default']
    TableSearch: typeof import('./src/components/common/tableSearch.vue')['default']
  }
}
